-- MARIAM ACADEMY
-- This schema matches the current Supabase database setup.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','teacher')),
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title_ar text not null,
  title_en text not null,
  description_ar text default '',
  description_en text default '',
  image_url text,
  language text default 'ar',
  is_published boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  title_ar text not null,
  title_en text not null,
  video_url text,
  pdf_url text,
  sort_order integer default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(student_id, course_id)
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  title_ar text not null,
  title_en text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  exam_id bigint references
